version: 2
updates:
  # Check for updates in npm package.json files
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "npm"

  # Check for updates in Python pip requirements.txt files
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"

  # Check for updates in GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"

  # Check for updates in Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"

  # Check for updates in NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - github
    labels:
      - "dependencies"
      - "nuget"
    registries:
      github:
        type: nuget-feed
        url: "https://nuget.pkg.github.com/LegitSecurity/index.json"
        username: bot-legit
        password: ${{secrets.GHCR_PAT}}

  # Check for updates in Maven pom.xml files
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "maven"

  # Check for updates in Gradle build.gradle files
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "gradle"

  # Check for updates in Composer composer.json files
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "composer"

  # Check for updates in Ruby Bundler Gemfile files
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "bundler"

  # Check for updates in Cargo Cargo.toml files
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "cargo"

  # Check for updates in Elixir Mix.exs files
  - package-ecosystem: "hex"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "hex"
